### PR TITLE
Regenerating SDKs following introspection of schemas.

### PR DESCRIPTION
**Pull request by JasonCWang**

### CODE REVIEW

**Comment by JasonCWang** [comment]
* **#12** <a href="https://app.graphite.dev/github/pr/lightsparkdev/flutter-sdk/12?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JasonCWang and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by zhenlu — APPROVED** [review]

**Comment by JasonCWang** [comment]
### Merge activity

* **Oct 11, 2:10 PM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/lightsparkdev/flutter-sdk/12).

**Comment by jklein24** [comment]
OK to drop this one - maybe should actually install the formatter just to avoid the extra PRs?

**Comment by jklein24** [comment]
Gah, this shouldn't have been merged :-(. @JasonCWang can you revert?

**Comment by JasonCWang** [comment]
The auto merger :( Yeah I will revert

**Comment by JasonCWang** [comment]
I was reverting the flutter changes manually, but I think I should just use dart to change the formatting back like you did. Sorry for the delay

**Comment by jklein24** [comment]
> I was reverting the flutter changes manually, but I think I should just use dart to change the formatting back like you did. Sorry for the delay

You can also actually just use the revert button above if you want
Screenshot 2024-10-11 at 11 59 07 AM

**Comment by JasonCWang** [comment]
Dang did not realize this... ;-(

**Pull request merged**
